name: CI/CD for Spring Boot on AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir e taggear a imagem Docker
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/spring-app:latest .

      - name: Push da imagem para o GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/spring-app:latest

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3

      - name: Conectar ao Azure AKS
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Obter credenciais do cluster AKS
        run: az aks get-credentials --resource-group seu-resource-group --name seu-cluster-aks

      - name: Aplicar configuração no Kubernetes
        run: kubectl apply -f deployment.yaml
