spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5432/db_parking
    username: postgres
    console:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
